### ISSUE TITLE
Issues with Arena

### ISSUE THREAD

**Issue by ianm8** [maksimKorzh/bbc#2]
Hi Maksym

I was running a test with my engine and noticed a couple of issues. The TC was Blitz 2/6 and BBC started using negative time so Arena aborted. Also sometimes BBC generates a null PV, eg:

2020-09-26 17:50:37.284<--2:info score cp 0 depth 10 nodes 2193409 time 2954 pv

Here is the log from two games:

[BBC1 vs Plankton64mt_04.txt](https://github.com/maksimKorzh/bbc/files/5287849/BBC1.vs.Plankton64mt_04.txt)

Cheers, Ian

**Comment by maksimKorzh** [comment]
Hi Ian

Thanks for your report.
Here're some plans on BBC development to make things a little bit more clear:
1. Improve evaluation
2. Beat VICE
3. Fix existing issues

By saying this I mean that the initial release is done only to claim that BBC is stronger than TSCP, that's it.
I didn't test it versus other engines yet, I mean at all, so these bugs are predictable.
I took timing from VICE and PV from TSCP, hence don't have that crystal clear understanding of all the detail on how they work.

If your engine can be compiled under linux you can send me your sources so I would test it on my side.
The next version should fix these errors.

**Comment by ianm8** [comment]
Hi Maksym

I don't have a version for Linux since I upgraded to multithreaded. I think my goals were similar to yours. I started out just wanting to equal TSCP then moved up from there. My primary goal was to create a version that runs on a microcontroller. Very addictive this chess programming lark.

Cheers, Ian


________________________________

**Comment by maksimKorzh** [comment]
Hi Ian

Cool. I will let you know as soon as fixes arrive!
feel free to track the series if you're interested:
https://www.youtube.com/watch?v=QUNP-UjujBM&list=PLmN0neTso3Jxh8ZIylk74JpwfiWNI76Cs

**Comment by maksimKorzh** [comment]
Here's the new version with bug fixes
https://github.com/maksimKorzh/bbc/blob/master/src/bbc_1.1.c
But if your engine is stornger than 2500 ELO then there's no much sense in playing matches.
New version should be around of VICE strength, probably slightly weaker.
