### ISSUE TITLE
UCI-responses sent too early

### ISSUE THREAD

**Issue by mvanthoor** [maksimKorzh/bbc#4]
Hi Maksim,

There's a small problem with BBC which could cause a problem in some user interfaces, now or in the future.

When the engine is started, it immediately sends "id name", "id author", and "uciok" to the user interface. However, the engine should wait until it receives 'uci' before sending those responses. It does sent them when receiving 'uci', but there may be a user interface that sees "uciok", thinks you're done, and then your engine won't have a name or an author when the GUI loads it.

Just remove sending the commands at startup and everything should be fine.

**Comment by maksimKorzh** [comment]
Hi Marcel

Thanks for pointing out. Fixed.
